source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
# gem 'dm-postgres-adapter'
gem 'rake'
gem 'tesseract-ocr'
gem 'json'
# gem 'carrierwave-datamapper', :require => 'carrierwave/datamapper'
# gem 'sinatra-activerecord'
gem 'mini_magick'
gem 'tesseract-ocr'
